/**
 * Excel's built-in pivot table style names.
 *
 * @group PivotTables
 */
export type PivotTableStyleName =
  'PivotStyleDark1' |
  'PivotStyleDark2' |
  'PivotStyleDark3' |
  'PivotStyleDark4' |
  'PivotStyleDark5' |
  'PivotStyleDark6' |
  'PivotStyleDark7' |
  'PivotStyleDark8' |
  'PivotStyleDark9' |
  'PivotStyleDark10' |
  'PivotStyleDark11' |
  'PivotStyleDark12' |
  'PivotStyleDark13' |
  'PivotStyleDark14' |
  'PivotStyleDark15' |
  'PivotStyleDark16' |
  'PivotStyleDark17' |
  'PivotStyleDark18' |
  'PivotStyleDark19' |
  'PivotStyleDark20' |
  'PivotStyleDark21' |
  'PivotStyleDark22' |
  'PivotStyleDark23' |
  'PivotStyleDark24' |
  'PivotStyleDark25' |
  'PivotStyleDark26' |
  'PivotStyleDark27' |
  'PivotStyleDark28' |
  'PivotStyleLight1' |
  'PivotStyleLight2' |
  'PivotStyleLight3' |
  'PivotStyleLight4' |
  'PivotStyleLight5' |
  'PivotStyleLight6' |
  'PivotStyleLight7' |
  'PivotStyleLight8' |
  'PivotStyleLight9' |
  'PivotStyleLight10' |
  'PivotStyleLight11' |
  'PivotStyleLight12' |
  'PivotStyleLight13' |
  'PivotStyleLight14' |
  'PivotStyleLight15' |
  'PivotStyleLight16' |
  'PivotStyleLight17' |
  'PivotStyleLight18' |
  'PivotStyleLight19' |
  'PivotStyleLight20' |
  'PivotStyleLight21' |
  'PivotStyleLight22' |
  'PivotStyleLight23' |
  'PivotStyleLight24' |
  'PivotStyleLight25' |
  'PivotStyleLight26' |
  'PivotStyleLight27' |
  'PivotStyleLight28' |
  'PivotStyleMedium1' |
  'PivotStyleMedium2' |
  'PivotStyleMedium3' |
  'PivotStyleMedium4' |
  'PivotStyleMedium5' |
  'PivotStyleMedium6' |
  'PivotStyleMedium7' |
  'PivotStyleMedium8' |
  'PivotStyleMedium9' |
  'PivotStyleMedium10' |
  'PivotStyleMedium11' |
  'PivotStyleMedium12' |
  'PivotStyleMedium13' |
  'PivotStyleMedium14' |
  'PivotStyleMedium15' |
  'PivotStyleMedium16' |
  'PivotStyleMedium17' |
  'PivotStyleMedium18' |
  'PivotStyleMedium19' |
  'PivotStyleMedium20' |
  'PivotStyleMedium21' |
  'PivotStyleMedium22' |
  'PivotStyleMedium23' |
  'PivotStyleMedium24' |
  'PivotStyleMedium25' |
  'PivotStyleMedium26' |
  'PivotStyleMedium27' |
  'PivotStyleMedium28';
