name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: # TODO: Before merging, stop running this action on PRs.

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npm run build:docs
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
